#!/usr/bin/env bash

# Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager

# xfce4-settings daemon
xfsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Start Compositing Manager
exec picom &

# Launch Polybar
bash ~/.config/openbox/themes/launch-bar.sh

## Notification Daemon
exec dunst &

# Launch Plank
# exec plank &

# Thunar Daemon
exec thunar --daemon &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

# User Friendly Network Menu
# nm-applet --indicator &

# User Friendly Bluetooth Menu
# blueman-applet &

# Configure power managment to always up
xset s off
xset -dpms
xset s noblank
pkill xss-lock
pkill betterlockscreen

bash ~/.config/openbox/themes/default/bgput.sh &
bash ~/.config/openbox/fix_wallpaper.sh &
